version: "3.9"

services:

  rest-api-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    networks:
      - service

  postgres:
    image: postgres:16.3                
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rest-api-service
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - service

volumes:
  pgdata:

networks:
  service:

