basePath: /
definitions:
  controller.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  controller.createArticleResponse:
    properties:
      id:
        type: integer
    type: object
  domain.Article:
    properties:
      description:
        maxLength: 1000
        type: string
      id:
        type: integer
      photos:
        items:
          type: string
        maxItems: 3
        type: array
      title:
        maxLength: 140
        type: string
      user_id:
        type: integer
    required:
    - description
    - photos
    - title
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a rest-api-boilerplate.
  title: rest-api-boilerplate
  version: "1.0"
paths:
  /article/create/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/domain.Article'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.createArticleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: CreateArticle creates new article
      tags:
      - articles
swagger: "2.0"
